// `docs/protocol-v5.md` from the protocol's model (`protocolModel.ts`): the
// transport and an example session (`protocolText.ts`), the handshake, the
// events in each direction, the frame types grouped as `envelope.ts` groups
// them, the error codes, the room and topic names, the limits, and what a
// client must do. Laid out as oxfmt lays out Markdown (`markdown.ts`).

import { code, paragraph, section, table } from "./markdown";
import type { EventDoc, ProtocolModel } from "./protocolModel";
import type { Field, Shape, TypeDoc } from "./protocolSource";
import {
  CLIENT_EVENTS_INTRO,
  CLIENT_RULES,
  DEFAULTS_INTRO,
  ERRORS_INTRO,
  EXAMPLE,
  HANDSHAKE_INTRO,
  INTRO,
  JSON_ONLY,
  LIMITS_INTRO,
  LIMITS_OUTCOMES,
  NAMES_INTRO,
  PACKETS,
  SERVER_EVENTS_INTRO,
  TRANSPORT,
  TYPE_PARAMETERS,
} from "./protocolText";

/** The first line of the document; only a file that starts with it is ever replaced. */
export const PROTOCOL_MARKER =
  "<!-- Generated by quickdraw-protocol from packages/core/src/protocol/envelope.ts and the sources beside it. Do not edit: change the source and run `bun run protocol:sync` in packages/core. -->";

type Blocks = (string | readonly string[])[];

/** Type text with `typeof X` written as X's value, and `(typeof X)[number]` as its values' union. */
function resolve(text: string, model: ProtocolModel): string {
  const valueOf = (name: string): string | undefined => model.constants.get(name)?.value;
  return text
    .replace(
      /\(typeof (\w+)\)\[number\]/g,
      (whole, name: string) => valueOf(name)?.split(", ").join(" | ") ?? whole,
    )
    .replace(/typeof (\w+)/g, (whole, name: string) => valueOf(name) ?? whole);
}

function fieldName(field: Field): string {
  return code(field.optional ? `${field.name}?` : field.name);
}

/** A table of fields; `extra` adds a column (the defaults of the hello's limits). */
function fieldTable(
  fields: readonly Field[],
  model: ProtocolModel,
  extra?: { readonly header: string; readonly cell: (field: Field) => string },
): string[] {
  const docs = fields.some((field) => field.doc !== "");
  const header = ["Field", "Type", ...(extra ? [extra.header] : []), ...(docs ? ["Meaning"] : [])];
  const rows = fields.map((field) => [
    fieldName(field),
    code(resolve(field.type, model)),
    ...(extra ? [extra.cell(field)] : []),
    ...(docs ? [field.doc] : []),
  ]);
  return table(header, rows);
}

function tupleTable(fields: readonly Field[], model: ProtocolModel): string[] {
  const rows = fields.map((field, index) => [
    field.name.startsWith("...") ? `${index} and after` : String(index),
    code(field.name.replace(/^\.\.\./, "")),
    code(resolve(field.type, model)),
  ]);
  return table(["Position", "Name", "Type"], rows);
}

/** One member of a union, on one line. */
function memberText(member: Shape, model: ProtocolModel): string {
  if (member.kind === "fields") {
    const fields = member.fields.map(
      (field) => `${field.name}${field.optional ? "?" : ""}: ${field.type}`,
    );
    return code(resolve(`{ ${fields.join("; ")} }`, model));
  }
  return code(resolve(member.kind === "text" ? member.text : "", model));
}

function shapeBlocks(shape: Shape, model: ProtocolModel): Blocks {
  switch (shape.kind) {
    case "fields":
      return shape.fields.length === 0 ? ["An empty object."] : [fieldTable(shape.fields, model)];
    case "tuple":
      return ["A JSON array:", tupleTable(shape.fields, model)];
    case "union":
      return shape.members.every((member) => member.kind === "text")
        ? [`One of ${shape.members.map((member) => memberText(member, model)).join(", ")}.`]
        : [
            "One of:",
            table(
              ["Shape"],
              shape.members.map((member) => [memberText(member, model)]),
            ),
          ];
    default:
      return [`${code(resolve(shape.text, model))}.`];
  }
}

function typeSection(
  type: TypeDoc,
  level: string,
  model: ProtocolModel,
  blocks: Blocks = shapeBlocks(type.shape, model),
): string[] {
  const doc = type.doc === "" ? [] : [paragraph(type.doc)];
  return section(`${level} ${code(type.name)}`, [...doc, ...blocks]);
}

/** The default a server announces for a field of the hello's limits, from `DEFAULT_LIMITS`. */
function limitDefault(model: ProtocolModel, type: string): ((field: Field) => string) | undefined {
  const prefix =
    type === "HelloLimits" ? "" : type === "HelloSubscriptionLimits" ? "subscriptions." : undefined;
  if (prefix === undefined) {
    return undefined;
  }
  // `maxSubscribeIds` is fixed, not a dispatcher limit.
  const fixed: Readonly<Record<string, string | undefined>> = {
    maxSubscribeIds: model.constants.get("MAX_SUBSCRIBE_IDS")?.value,
  };
  return (field) => model.defaults.get(`${prefix}${field.name}`) ?? fixed[field.name] ?? "";
}

function handshakeSection(model: ProtocolModel): string[] {
  const version = model.constants.get("PROTOCOL_VERSION")?.value ?? "";
  const types = [...model.types.values()].filter((type) => type.source === "version");
  return [
    ...section("## Handshake", [
      paragraph(HANDSHAKE_INTRO),
      `A 5.0 server speaks protocol ${code(version)} and refuses a client that names any other.`,
    ]),
    ...types.flatMap((type) => {
      const defaults = limitDefault(model, type.name);
      const blocks =
        defaults !== undefined && type.shape.kind === "fields"
          ? [fieldTable(type.shape.fields, model, { header: "Default", cell: defaults })]
          : undefined;
      return typeSection(type, "###", model, blocks);
    }),
  ];
}

function ackText(event: EventDoc, model: ProtocolModel): string {
  const reply = code(resolve(event.reply ?? "", model));
  return event.ack === "none" ? "none" : event.ack === "optional" ? `${reply}, when asked` : reply;
}

function eventsSection(
  heading: string,
  intro: string,
  events: readonly EventDoc[],
  model: ProtocolModel,
): string[] {
  const acked = events.some((event) => event.ack !== "none");
  const header = ["Event", "Payload", ...(acked ? ["Acknowledgement"] : []), "Meaning"];
  const rows = events.map((event) => [
    code(event.name),
    code(resolve(event.payload, model)),
    ...(acked ? [ackText(event, model)] : []),
    event.doc,
  ]);
  return section(heading, [paragraph(intro), table(header, rows)]);
}

/** The names of the model's types `text` mentions. */
function mentioned(text: string, model: ProtocolModel): string[] {
  return [...text.matchAll(/\b[A-Z]\w*/g)]
    .map(([name]) => name)
    .filter((name) => model.types.has(name));
}

function shapeText(shape: Shape): string {
  switch (shape.kind) {
    case "fields":
    case "tuple":
      return shape.fields.map((field) => field.type).join(" ");
    case "union":
      return shape.members.map(shapeText).join(" ");
    default:
      return shape.text;
  }
}

/** The types the events reach, directly or through other types. */
function reachable(model: ProtocolModel): ReadonlySet<string> {
  const events = [...model.clientEvents, ...model.serverEvents];
  const queue = events.flatMap((event) =>
    mentioned(`${event.payload} ${event.reply ?? ""}`, model),
  );
  const seen = new Set<string>();
  for (let name = queue.pop(); name !== undefined; name = queue.pop()) {
    const type = model.types.get(name);
    if (type !== undefined && !seen.has(name)) {
      seen.add(name);
      queue.push(...mentioned(shapeText(type.shape), model));
    }
  }
  return seen;
}

/** The frame types the events reach, grouped as `envelope.ts` groups them. */
function typesSection(model: ProtocolModel): string[] {
  const reached = reachable(model);
  const groups = new Map<string, TypeDoc[]>();
  for (const type of model.types.values()) {
    if (reached.has(type.name) && (type.source === "envelope" || type.source === "access")) {
      const group = type.group ?? "Common";
      groups.set(group, [...(groups.get(group) ?? []), type]);
    }
  }
  return [
    ...section("## Frame types", [paragraph(TYPE_PARAMETERS)]),
    ...[...groups].flatMap(([group, types]) => [
      `### ${group}`,
      "",
      ...types.flatMap((type) => typeSection(type, "####", model)),
    ]),
  ];
}

function errorsSection(model: ProtocolModel): string[] {
  const rows = model.errors.map((error) => [code(error.code), error.status, error.meaning]);
  const internal = model.constants.get("INTERNAL_MESSAGE")?.value ?? "";
  const types = [...model.types.values()].filter(
    (type) => type.source === "errors" && type.name !== "ErrorCode",
  );
  return [
    ...section("## Errors", [
      paragraph(ERRORS_INTRO),
      table(["Code", "HTTP", "Meaning"], rows),
      `An \`INTERNAL\` error always carries the message ${code(internal)} and no \`data\`, whatever failed on the server.`,
    ]),
    ...types.flatMap((type) => typeSection(type, "###", model)),
  ];
}

function namesSection(model: ProtocolModel): string[] {
  const rows = model.names.map((name) => [
    code(name.name),
    name.formats.map(code).join(" or "),
    name.doc,
  ]);
  // A list item: its doc's later lines are indented under it.
  const item = (name: string): string => {
    const found = model.constants.get(name);
    const values = (found?.value ?? "").split(", ").map(code).join(", ");
    return `- ${code(name)} is ${values}. ${paragraph(found?.doc ?? "").replace(/\n/g, "\n  ")}`;
  };
  return section("## Rooms and topics", [
    paragraph(NAMES_INTRO),
    table(["Builder", "Name", "Meaning"], rows),
    [item("RESERVED_ROOM_PREFIXES"), item("SERVICE_TOPIC")],
  ]);
}

function limitsSection(model: ProtocolModel): string[] {
  const row = (name: string, unit: string): string[] => {
    const found = model.constants.get(name);
    if (found === undefined) {
      throw new Error(
        `quickdraw-protocol: no protocol source declares ${name}, which it documents`,
      );
    }
    return [code(name), `${found.value}${unit}`, found.doc];
  };
  const header = ["Constant", "Value", "Meaning"];
  return section("## Limits", [
    paragraph(LIMITS_INTRO),
    table(header, [
      row("MAX_SUBSCRIBE_IDS", " ids"),
      row("MAX_ITEM_IDS", " ids"),
      row("MAX_SCOPE_LENGTH", " characters"),
      row("MAX_STREAMS_PER_SOCKET", " feeds"),
      row("CHANNEL_ABUSE_WINDOW_MS", " ms"),
      row("CHANNEL_ABUSE_MULTIPLIER", " times the channel's rate"),
    ]),
    paragraph(DEFAULTS_INTRO),
    table(header, [
      row("DEFAULT_MAX_REQUESTS", " events a minute per socket"),
      row("CHANNEL_DEFAULT_RATE", " messages a second per socket"),
      row("DEFAULT_BACKOFF_MS", " ms"),
    ]),
    paragraph(LIMITS_OUTCOMES),
    `The socket rate limiter never counts ${model.unlimited.map(code).join(", ")}.`,
  ]);
}

/** The whole document. */
export function renderProtocol(model: ProtocolModel): string {
  const lines = [
    PROTOCOL_MARKER,
    "",
    ...section(INTRO, []),
    ...section(TRANSPORT, [
      table(
        ["Packet", "Meaning", "Sent by"],
        PACKETS.map(([packet, meaning, by]) => [code(packet), meaning, by]),
      ),
      paragraph(JSON_ONLY),
    ]),
    ...handshakeSection(model),
    ...section(EXAMPLE, []),
    ...eventsSection("## Client to server", CLIENT_EVENTS_INTRO, model.clientEvents, model),
    ...eventsSection("## Server to client", SERVER_EVENTS_INTRO, model.serverEvents, model),
    ...section(CLIENT_RULES, []),
    ...typesSection(model),
    ...errorsSection(model),
    ...namesSection(model),
    ...limitsSection(model),
  ];
  return `${lines.join("\n").trimEnd()}\n`;
}
