// The prose of `docs/protocol-v5.md` that no protocol source holds: the
// Socket.IO framing a client without a Socket.IO library writes, an example
// session, and what a client must do. The frames, names, codes, limits and
// defaults the prose mentions are rendered from the sources
// (`protocolRender.ts`); keep this text free of numbers they hold.

/** The document's title and introduction. */
export const INTRO = `# quickdraw protocol v5

How a client talks to a quickdraw 5.0 server, for clients in any language.
A TypeScript or JavaScript app uses the typed client of
\`@fitzzero/quickdraw-core/client\`, which speaks this protocol for it.
[clients.md](clients.md) lists the ways in, and
[examples/godot](../examples/godot) holds a GDScript client written from
this document.

The frames below are generated from
[\`packages/core/src/protocol/envelope.ts\`](../packages/core/src/protocol/envelope.ts),
which is normative (RFC 0003 section 8): where this document and the code
disagree, the code wins. Do not edit this file; change the source and run
\`bun run protocol:sync\` in \`packages/core\` (CI fails when it is stale).`;

/** How Socket.IO 4 frames the protocol over a WebSocket. */
export const TRANSPORT = `## Transport

Socket.IO 4 over a WebSocket: Engine.IO protocol 4 packets, Socket.IO
packets inside them, every payload JSON. A client needs no Socket.IO
library; this section is all the framing a WebSocket-only client writes and
reads (no HTTP long polling, no binary attachments).

1. Open a WebSocket to \`ws://<host>/socket.io/?EIO=4&transport=websocket\`
   (\`wss://\` over TLS; the path is the server's Socket.IO \`path\`,
   \`/socket.io\` unless the app changed it). Each WebSocket text message is
   one packet.
2. The server opens with Engine.IO's OPEN packet, \`0\` and a JSON object:
   \`0{"sid":"…","upgrades":[],"pingInterval":25000,"pingTimeout":20000,"maxPayload":1000000}\`.
3. The client connects to the main namespace with Socket.IO's CONNECT
   packet, \`40\`, carrying the handshake's \`auth\` (below):
   \`40{"token":"…","qd":{"protocol":5,"client":"my-game/1.0"}}\`.
4. The server accepts with CONNECT, \`40{"sid":"…"}\`, then sends
   \`qd:hello\`. Or it refuses with CONNECT_ERROR,
   \`44{"message":"…","data":{"code":"…"}}\`, and the socket is not connected.
5. An event is \`42\` and a JSON array, \`["<event>", <payload>]\`. An event
   that asks for an acknowledgement puts its ack id between the two:
   \`42<ackId>["qd:call",{…}]\`, and the server answers with an ACK packet,
   \`43<ackId>[<reply>]\`. Ack ids are the client's own counter for its
   connection; they are not a call's \`id\`.
6. The server sends PING, \`2\`, every \`pingInterval\` milliseconds; answer
   PONG, \`3\`, or the server closes the connection after \`pingTimeout\`. A
   client that hears nothing for \`pingInterval + pingTimeout\` has lost the
   connection.
7. A client leaves with Socket.IO's DISCONNECT, \`41\`, then closes the
   WebSocket itself. The server ends a socket with \`41\` and closes the
   WebSocket after it; a message longer than \`maxPayload\` bytes closes it
   too.`;

/** The packets a WebSocket-only client sees: the text they start with, what they are, who sends them. */
export const PACKETS: readonly (readonly [string, string, string])[] = [
  ["0{…}", "Engine.IO OPEN: the connection's settings", "server"],
  ["2", "Engine.IO PING", "server"],
  ["3", "Engine.IO PONG", "client"],
  ["40{…}", "Socket.IO CONNECT: the handshake, answered with the socket's id", "both"],
  ["41", "Socket.IO DISCONNECT", "both"],
  ["42[…]", "Socket.IO EVENT without an acknowledgement", "both"],
  ["42<ackId>[…]", "Socket.IO EVENT that asks for an acknowledgement", "client"],
  ["43<ackId>[…]", "Socket.IO ACK: the acknowledgement of event `ackId`", "server"],
  ["44{…}", "Socket.IO CONNECT_ERROR: the handshake was refused", "server"],
];

/** The JSON-only rule, after the packet table. */
export const JSON_ONLY = `The server writes JSON only: it uses the JSON-only Socket.IO parser (RFC
0003 section 8.4), so it never sends Socket.IO's binary packets (\`45\`,
\`46\`), unless the app opted into binary, which \`qd:hello\`'s \`features\`
then lists as \`"binary"\`.`;

/** One short session, frame by frame. */
export const EXAMPLE = `## Example session

A client signs in with a token, calls a method that joins a lobby, sends on
a channel that requires the lobby, and hears an event and a presence frame.
\`>\` is what the client sends, \`<\` what it receives:

\`\`\`text
< 0{"sid":"a1","upgrades":[],"pingInterval":25000,"pingTimeout":20000,"maxPayload":1000000}
> 40{"qd":{"client":"my-game/1.0","protocol":5},"token":"…"}
< 40{"sid":"b2"}
< 42["qd:hello",{"protocol":5,"server":"5.0.0","serverId":"c3f1…","limits":{…},"features":[],"userId":"ada","serviceAccess":{}}]
> 421["qd:call",{"id":0,"s":"lobbyService","m":"join","i":{"lobby":"main"}}]
< 42["qd:presence",{"room":"lobby:main","users":["ada"]}]
< 431[{"ok":true,"d":{"lobby":"main","players":["ada"]}}]
> 42["qd:ch",["lobbyService","move",{"dx":1,"dy":0}]]
< 42["qd:event",["lobbyService","moved",{"userId":"ada","x":1,"y":0}]]
< 2
> 3
\`\`\``;

/** What a client must do to stay within the server's rules. */
export const CLIENT_RULES = `## What a client must do

- Wait for \`qd:hello\` before the first call: it says who the socket acts for
  (\`userId\`, \`serviceAccess\`) and the limits to stay within. Each hello is a
  new socket in no app room: make the joining calls again after every one. A
  \`serverId\` other than the last hello's means the server restarted (or,
  behind a cluster, another node answered): its state starts over.
- Give each \`qd:call\` an \`id\` no call in flight on the socket has; \`qd:cancel\`
  names it, and the call's acknowledgement still arrives. Send it with an ack
  id: the server ignores a \`qd:call\` sent without one, with no reply and no
  error. Wait for an acknowledgement at most \`limits.callTimeoutMs\` and 2
  seconds more: the server answers \`TIMEOUT\` itself before that.
- Back off on \`RATE_LIMITED\`: wait \`e.data.retryAfterMs\` (the default
  below when it is absent) and a random part of it more before sending that
  kind of work again, calls or subscription events. A client that retries at
  once loops, and in development the server names it in a \`repeated-call\`
  warning.
- Keep the subscription events within \`limits.subscriptions\`: at most
  \`maxInFlight\` awaiting their acknowledgement, a \`qd:sub\` naming at most
  \`limits.maxSubscribeIds\` ids and a \`qd:col:items\` at most
  \`MAX_ITEM_IDS\` (below); a frame naming more fails whole with
  \`VALIDATION\`.
- Send \`qd:ch\` and forget it: there is no acknowledgement and no error, so
  never wait for one, and drop a message rather than queue it while the
  connection is backed up (Socket.IO calls that volatile). The server drops
  a message silently when it is over the channel's rate, fails its schema,
  or fails its \`requires\`, and ends the socket of a client that keeps
  sending far over a channel's rate (below).
- Apply \`qd:e\` and \`qd:c\` frames by \`rev\`, not by arrival: behind a
  cluster, frames from two nodes can arrive out of order.
- App rooms are per socket. A method joins the socket that called it
  (\`ctx.rooms.join\`), so a channel that requires a room needs the joining
  call made over the same connection, and after a reconnect the new socket
  is in no app room until a call joins it again. Subscriptions are per
  socket too: subscribe again after a reconnect, sending the revisions held.
- On \`qd:rotate\`, pick a random moment within \`withinMs\` and stay
  connected until then: calls are still answered on that socket. At that
  moment, disconnect and reconnect with a fresh handshake, so the server's
  clients come back spread over the window.
- When the handshake is refused, reconnecting with the same client and
  credentials is refused again: \`PROTOCOL_MISMATCH\` needs a client that
  speaks the server's protocol, \`UNAUTHENTICATED\` other credentials.`;

/** What the type parameters of the frame types stand for. */
export const TYPE_PARAMETERS = `Keys are short: \`s\` a service's name, \`m\` a method's, \`c\` a collection's,
\`i\` an input, \`d\` data, \`e\` an error, \`v\` a version, \`rev\` a revision,
\`t\` a frame's kind. Type parameters stand for what the app's contracts
define: \`Output\` a method's output, \`Row\` a service's row as its
projection, \`Item\` a collection's or a stream's item, \`Payload\` a
channel's or an event's payload. A field marked \`?\` may be absent.`;

/** Before the handshake's types. */
export const HANDSHAKE_INTRO = `The client sends \`HandshakeAuth\` as the CONNECT packet's \`auth\`. The
server answers with \`qd:hello\` (\`HelloFrame\`), or refuses the connection
with CONNECT_ERROR, whose \`data\` is \`ProtocolMismatch\` or
\`AuthenticationRefused\`. How \`token\` is checked is the app's: the server's
\`authenticate\` reads the whole \`auth\` object, and a browser's cookies reach
it too.`;

/** Before the client events. */
export const CLIENT_EVENTS_INTRO = `Each event's payload is the one argument after its name. An event with an
acknowledgement is sent with an ack id, and its reply arrives as the ACK's
one argument; "when asked" means the server acknowledges it only when the
client sends an ack id.`;

/** Before the server events. */
export const SERVER_EVENTS_INTRO = `The server never asks for an acknowledgement. A client listens for each event
once and routes by the frame's keys (\`s\`, \`id\`, \`c\`, \`scope\`, \`room\`).`;

/** Before the error codes. */
export const ERRORS_INTRO = `A refused acknowledgement is \`Failure\`: \`{ ok: false, e }\`, with \`e\` a
\`WireError\`. Its code, and the HTTP status the HTTP transport answers the
same failure with:`;

/** Before the room and topic names. */
export const NAMES_INTRO = `A client never joins a room by name: the server puts its socket in rooms as
it subscribes, watches a topic or calls a method that joins one. The names
show where a frame carries one: \`qd:presence\`'s \`room\` is an app room a
method joined, and \`qd:watch\`'s \`topic\` is the service topic or a
collection scope's.`;

/** Before the table of fixed limits. */
export const LIMITS_INTRO = `A server announces its call and subscription limits in \`qd:hello\` (above):
the defaults shown there are the server's own, and an app may set others,
so read them from the hello. The limits below are fixed: every 5.0 server
holds them, and no option changes them.`;

/** Before the table of defaults. */
export const DEFAULTS_INTRO = `These are defaults. An app changes the socket rate limiter with
\`createServer({ rateLimit })\` and a channel's rate with its contract's
\`ratePerSecond\` and \`burst\` (twice the rate when absent); the backoff is
the client's own, for an answer that names no wait:`;

/** After the tables: what a client meets past a limit. */
export const LIMITS_OUTCOMES = `A \`qd:sub\` naming more than \`MAX_SUBSCRIBE_IDS\` ids, or a
\`qd:col:items\` more than \`MAX_ITEM_IDS\`, fails whole with \`VALIDATION\`; a
\`qd:stream:sub\` past \`MAX_STREAMS_PER_SOCKET\` feeds fails with \`CONFLICT\`.
A socket whose \`qd:ch\` messages dropped for one channel's rate within
\`CHANNEL_ABUSE_WINDOW_MS\` exceed \`CHANNEL_ABUSE_MULTIPLIER\` times that rate
is disconnected (Socket.IO DISCONNECT, \`41\`, then the WebSocket closes): that
is sustained flooding, not a burst. As after any DISCONNECT the server
sends, a client does not reconnect on its own.`;
