// The Markdown `quickdraw-docs` writes: one page per service and an index,
// read from the contracts, laid out as oxfmt lays out Markdown
// (`markdown.ts`), so `--check` does not report formatting as drift. With
// `--services`, each page also says who may call what, read from the
// services' definitions (`access.ts`).

import {
  DEFAULT_COLLECTION_LIMIT,
  DEFAULT_COLLECTION_MAX_LIMIT,
  type CollectionDef,
} from "../contract/collections";
import type { AnyContract } from "../contract/defineContract";
import type { MethodDef, MethodOutput } from "../contract/methods";
import {
  CHANNEL_DEFAULT_RATE,
  isScopedStream,
  type ChannelDef,
  type EventDef,
  type StreamAccess,
  type StreamDef,
} from "../contract/realtime";
import { isStandardSchema, type StandardSchemaV1 } from "../contract/standardSchema";
import {
  accessFormText,
  collectionAccessText,
  policyText,
  watchAccessText,
  type ServiceDoc,
} from "./access";
import { code, list, paragraph, section, table } from "./markdown";
import {
  jsonSchemaOf,
  NO_JSON_SCHEMA,
  schemaFields,
  schemaText,
  type SchemaField,
} from "./schemaText";

/** The first line of every generated file; only files that start with it are ever replaced or removed. */
export const GENERATED_MARKER =
  "<!-- Generated by quickdraw-docs from the app's contracts. Do not edit: change the contract and run quickdraw-docs again. -->";

/**
 * What `--services` adds to a page: who may call what, from the service the
 * services module defines under the contract's name (`undefined`: none).
 */
export interface AccessInfo {
  readonly service: ServiceDoc | undefined;
}

/** True when the schema accepts `undefined`: a method that takes no input. */
function acceptsUndefined(schema: StandardSchemaV1): boolean {
  try {
    const result: unknown = schema["~standard"].validate(undefined);
    return (
      typeof result === "object" &&
      result !== null &&
      !("then" in result) &&
      (result as { readonly issues?: unknown }).issues === undefined
    );
  } catch {
    return false;
  }
}

function typeOf(schema: unknown, mode: "input" | "output"): string {
  const json = jsonSchemaOf(schema, mode);
  return json === undefined ? NO_JSON_SCHEMA : schemaText(json);
}

/** A field table: name, type, and the optional columns that hold something. */
function fieldTable(
  fields: readonly SchemaField[],
  levels: Readonly<Record<string, string>> = {},
): string[] {
  const hasLevels = fields.some((field) => levels[field.name] !== undefined);
  const hasNotes = fields.some((field) => field.notes !== "");
  const header = ["Field", "Type", ...(hasLevels ? ["Level"] : []), ...(hasNotes ? ["Notes"] : [])];
  const rows = fields.map((field) => [
    code(field.optional ? `${field.name}?` : field.name),
    code(field.type),
    ...(hasLevels ? [levels[field.name] ?? ""] : []),
    ...(hasNotes ? [field.notes] : []),
  ]);
  return table(header, rows);
}

/** A row schema's fields as a table, or its type when it has no properties. */
function shapeBlock(
  schema: unknown,
  levels: Readonly<Record<string, string>> = {},
): string | string[] {
  const json = jsonSchemaOf(schema, "output");
  if (json === undefined) {
    return `Its schema cannot describe itself as JSON Schema: ${code(NO_JSON_SCHEMA)}.`;
  }
  const fields = schemaFields(json);
  return fields === undefined ? code(schemaText(json)) : fieldTable(fields, levels);
}

function entitySection(contract: AnyContract): string[] {
  if (contract.entity === undefined) {
    return section("## Entity", [
      "None: an RPC-only service, without projections, field levels or collections.",
    ]);
  }
  const levels = contract.fields;
  const tiers =
    Object.keys(levels).length === 0
      ? []
      : ["A caller receives a field only with at least its level on the row."];
  return section("## Entity", [shapeBlock(contract.entity, levels), ...tiers]);
}

function projectionsSection(contract: AnyContract): string[] {
  const names = Object.keys(contract.projections);
  if (names.length === 0) {
    return [];
  }
  return [
    "## Projections",
    "",
    ...names.flatMap((name) =>
      section(`### ${code(name)}`, [shapeBlock(contract.projections[name])]),
    ),
  ];
}

function outputText(output: MethodOutput): string {
  if (isStandardSchema(output)) {
    return code(typeOf(output, "output"));
  }
  if (typeof output === "string") {
    return `one row as the ${code(output)} projection`;
  }
  return output.kind === "nullable"
    ? `one row as the ${code(output.projection)} projection, or ${code("null")}`
    : `rows as the ${code(output.projection)} projection`;
}

function inputBlocks(method: MethodDef): (string | string[])[] {
  const json = jsonSchemaOf(method.input, "input");
  if (json === undefined) {
    return [acceptsUndefined(method.input) ? "Input: none." : `Input: ${code(NO_JSON_SCHEMA)}.`];
  }
  const fields = schemaFields(json);
  return fields === undefined
    ? [`Input: ${code(schemaText(json))}.`]
    : ["Input:", fieldTable(fields)];
}

function kindLine(method: MethodDef): string {
  if (method.watch === undefined) {
    return method.kind === "query" ? "A query." : "A mutation.";
  }
  if (method.watch === "service") {
    return "A query that watches its service: a cached result is fetched again after every change to the service's rows, collections or the models it writes.";
  }
  if ("service" in method.watch) {
    const models = method.watch.service.map(code).join(", ");
    return `A query that watches its service's writes to ${models}: a cached result is fetched again after a change to one of them.`;
  }
  return `A query that watches the ${code(method.watch.collection)} collection: a cached result is fetched again when the scope its input names changes.`;
}

/** Who may call a method, and its `rowless`, when the page documents access. */
function methodAccess(name: string, access: AccessInfo | undefined): string[] {
  const method = access?.service?.methods.get(name);
  if (method === undefined) {
    return [];
  }
  const rowless = method.rowless
    ? [
        `${code("rowless")}: every caller the form admits may reach any row its input names, on purpose.`,
      ]
    : [];
  return [`Access: ${accessFormText(method.access)}.`, ...rowless];
}

function methodSection(name: string, method: MethodDef, access: AccessInfo | undefined): string[] {
  const described = method.describe === undefined ? [] : [paragraph(method.describe)];
  return section(`### ${code(name)}`, [
    ...described,
    kindLine(method),
    ...methodAccess(name, access),
    ...inputBlocks(method),
    `Output: ${outputText(method.output)}.`,
  ]);
}

function methodsSection(contract: AnyContract, access: AccessInfo | undefined): string[] {
  const entries = Object.entries(contract.methods);
  if (entries.length === 0) {
    return [];
  }
  return [
    "## Methods",
    "",
    ...entries.flatMap(([name, method]) => methodSection(name, method, access)),
  ];
}

function scopeText(scope: CollectionDef["scope"]): string {
  if (typeof scope === "string") {
    return `the ${code(scope)} column`;
  }
  const via = `${code(scope.scope)} of the ${code(scope.model)} rows whose ${code(scope.entry)} is the item's id`;
  return scope.refreshEntry === true
    ? `${via}; a write to those rows sends the item again to every scope that holds it`
    : via;
}

function whereText(where: CollectionDef["where"]): string | undefined {
  if (where === undefined || Object.keys(where).length === 0) {
    return undefined;
  }
  return Object.entries(where)
    .map(([column, value]) => code(`${column} = ${JSON.stringify(value)}`))
    .join(", ");
}

function optionTable(rows: readonly (readonly [string, string | undefined])[]): string[] {
  return table(
    ["Option", "Value"],
    rows.filter((row): row is readonly [string, string] => row[1] !== undefined),
  );
}

function collectionSection(
  name: string,
  collection: CollectionDef,
  access: AccessInfo | undefined,
): string[] {
  const views = collection.views === undefined ? [] : Object.keys(collection.views);
  const limit = collection.limit ?? DEFAULT_COLLECTION_LIMIT;
  const maxLimit = collection.maxLimit ?? DEFAULT_COLLECTION_MAX_LIMIT;
  const served = access?.service?.collections.get(name);
  return section(`### ${code(name)}`, [
    optionTable([
      ["Scope", scopeText(collection.scope)],
      ["Item", code(collection.item)],
      [
        "Order",
        collection.order.map(([column, direction]) => `${code(column)} ${direction}`).join(", "),
      ],
      ["Where", whereText(collection.where)],
      ["Index", collection.index === undefined ? undefined : list(collection.index)],
      ["Views", views.length === 0 ? undefined : list(views)],
      [
        "Access",
        served === undefined
          ? (collection.access ?? "Read (default)")
          : collectionAccessText(served),
      ],
      ["Page size", `${limit}, at most ${maxLimit}`],
    ]),
  ]);
}

function collectionsSection(contract: AnyContract, access: AccessInfo | undefined): string[] {
  const entries = Object.entries(contract.collections);
  if (entries.length === 0) {
    return [];
  }
  return [
    "## Collections",
    "",
    "Live lists of the service's rows, one per scope value.",
    "",
    ...entries.flatMap(([name, collection]) => collectionSection(name, collection, access)),
  ];
}

function accessText(access: StreamAccess | undefined): string {
  if (access === undefined) {
    return "none: closed to every client";
  }
  if (typeof access === "string") {
    return code(JSON.stringify(access));
  }
  if (access.room !== undefined) {
    const { room } = access;
    if (typeof room === "string") {
      return code(`{ room: "${room}" }`);
    }
    return typeof room === "function"
      ? code("{ room: (scope) => ... }")
      : code(`{ room: { prefix: "${room.prefix}" } }`);
  }
  if (access.scope !== undefined) {
    return code(`{ scope: "${access.scope}", of: ${access.of.name} }`);
  }
  const parts = [
    access.service === undefined ? undefined : `service: "${access.service}"`,
    access.entry === undefined ? undefined : `entry: "${access.entry}"`,
  ].filter((part) => part !== undefined);
  return code(`{ ${parts.join(", ")} }`);
}

function seedText(seed: number | undefined, computed: boolean): string {
  if (computed) {
    return "computed by the service when a socket subscribes";
  }
  if (seed === undefined || seed === 0) {
    return seed === undefined ? "none (default)" : "none";
  }
  return seed === 1 ? "the latest item" : `the latest ${seed} items`;
}

function streamSection(name: string, stream: StreamDef, access: AccessInfo | undefined): string[] {
  const scoped = isScopedStream(stream);
  const served = access?.service?.streams.get(name);
  return section(`### ${code(name)}`, [
    optionTable([
      ["Item", code(typeOf(stream.item, "output"))],
      ["Scope", scoped ? `one feed per ${code(stream.scope ?? "")}` : "one global feed"],
      ["Seed", seedText(stream.seed, served?.computedSeed === true)],
      ["Volatile", stream.volatile === true ? "yes" : "no"],
      ["Access", accessText(stream.access)],
      [
        "Checked",
        served === undefined
          ? undefined
          : served.validate === "development"
            ? `in development only (${code('validate: "development"')})`
            : "always",
      ],
    ]),
  ]);
}

function requiresText(requires: ChannelDef["requires"]): string | undefined {
  if (requires === undefined) {
    return undefined;
  }
  const selector = (value: unknown): string =>
    typeof value === "string" ? code(value) : "a function of the payload";
  if (requires.room !== undefined) {
    return typeof requires.room === "string"
      ? `the sending socket in the app room ${code(requires.room)}`
      : "the sending socket in the app room a function of the payload names";
  }
  return requires.collection === undefined
    ? `a subscription to the row ${selector(requires.entity)} names`
    : `a subscription to the ${code(requires.collection)} scope ${selector(requires.scope)} names`;
}

function channelSection(
  name: string,
  channel: ChannelDef,
  access: AccessInfo | undefined,
): string[] {
  const rate = channel.ratePerSecond ?? CHANNEL_DEFAULT_RATE;
  const served = access?.service?.channels.has(name) === true;
  return section(`### ${code(name)}`, [
    optionTable([
      ["Payload", code(typeOf(channel.payload, "input"))],
      [
        "Rate",
        `${rate} a second per socket${channel.ratePerSecond === undefined ? " (default)" : ""}`,
      ],
      [
        "Burst",
        channel.burst === undefined ? `${Math.max(1, 2 * rate)} (default)` : String(channel.burst),
      ],
      ["Requires", requiresText(channel.requires)],
      ["Access", served ? accessFormText(access?.service?.channels.get(name)) : undefined],
    ]),
  ]);
}

function eventSection(name: string, event: EventDef): string[] {
  return section(`### ${code(name)}`, [
    optionTable([["Payload", code(typeOf(event.payload, "output"))]]),
  ]);
}

function membersSection<Def>(
  heading: string,
  intro: string,
  members: Readonly<Record<string, Def>>,
  render: (name: string, def: Def) => string[],
): string[] {
  const entries = Object.entries(members);
  return entries.length === 0
    ? []
    : [heading, "", intro, "", ...entries.flatMap(([name, def]) => render(name, def))];
}

/** The fields a caller needs a level on the row to receive, as `name` (level). */
function fieldLevelsText(contract: AnyContract): string {
  const tiers = Object.entries(contract.fields);
  return tiers.length === 0
    ? "none: every caller who may read a row receives all of it"
    : tiers.map(([field, level]) => `${code(field)}: ${String(level)}`).join(", ");
}

/** The page's "Access" section, with `--services`: the service's policy, bypass, topic and field levels. */
function accessSection(contract: AnyContract, access: AccessInfo | undefined): string[] {
  if (access === undefined) {
    return [];
  }
  const { service } = access;
  if (service === undefined) {
    return section("## Access", [
      `The services module defines no ${code(contract.name)}: who may call its methods is not documented.`,
    ]);
  }
  return section("## Access", [
    optionTable([
      ["Row policy", policyText(service.policy)],
      [
        "Service-wide Admin",
        service.adminBypass
          ? "passes every check of the service"
          : `passes only the forms that name ${code("service")} (${code("adminBypass: false")})`,
      ],
      ["Change topic", watchAccessText(service.watchAccess)],
      ["Field levels", fieldLevelsText(contract)],
    ]),
    "Each method below says who may call it.",
  ]);
}

/**
 * One service's page: its entity, projections, methods, collections,
 * streams, channels and events, and with `access` (`--services`) who may
 * call what.
 */
export function renderService(contract: AnyContract, access?: AccessInfo): string {
  const lines = [
    GENERATED_MARKER,
    "",
    `# ${contract.name}`,
    "",
    ...accessSection(contract, access),
    ...entitySection(contract),
    ...projectionsSection(contract),
    ...methodsSection(contract, access),
    ...collectionsSection(contract, access),
    ...membersSection(
      "## Streams",
      "Feeds of items the server appends, each subscriber starting from the latest few.",
      contract.streams,
      (name, stream: StreamDef) => streamSection(name, stream, access),
    ),
    ...membersSection(
      "## Channels",
      "Fire-and-forget messages from clients, dropped over the rate.",
      contract.channels,
      (name, channel: ChannelDef) => channelSection(name, channel, access),
    ),
    ...membersSection(
      "## Events",
      "Typed events the server sends to the sockets in a room.",
      contract.events,
      eventSection,
    ),
  ];
  return `${lines.join("\n").trimEnd()}\n`;
}

/** The file a service's page is written to: its name, made safe for a file name. */
export function fileOf(contract: AnyContract): string {
  return `${contract.name.replace(/[^\w.-]/g, "-")}.md`;
}

/** The index page: every service with a link to its page and its members counted. */
export function renderIndex(contracts: readonly AnyContract[]): string {
  const count = (members: object): string => String(Object.keys(members).length);
  const rows = contracts.map((contract) => [
    `[${contract.name}](${fileOf(contract)})`,
    count(contract.methods),
    count(contract.collections),
    count(contract.streams),
    count(contract.channels),
    count(contract.events),
  ]);
  const lines = [
    GENERATED_MARKER,
    "",
    "# API reference",
    "",
    "One page per service, generated from its contract by `quickdraw-docs`.",
    "",
    ...table(["Service", "Methods", "Collections", "Streams", "Channels", "Events"], rows),
  ];
  return `${lines.join("\n")}\n`;
}
