// The package version, also announced by the server in `qd:hello`.
export { QUICKDRAW_VERSION } from "./version";

// Contracts (RFC 0003 section 2). Plain data plus schemas: everything below is
// browser-safe, with no Node built-ins, React or server code.
export type { AccessLevel, ACE, ACL } from "./contract/access";
export { consoleLogger, type Logger } from "./contract/logger";
export {
  hasJsonSchema,
  isStandardSchema,
  validate,
  type InferInput,
  type InferOutput,
  type StandardJSONSchemaV1,
  type StandardSchemaV1,
  type StandardSchemaWithJSON,
  type StandardTypedV1,
  type ValidationIssue,
  type ValidationResult,
} from "./contract/standardSchema";
export {
  listOf,
  mutation,
  nullable,
  query,
  type EntityProjection,
  type MethodDef,
  type MethodKind,
  type MethodOutput,
  type MutationDef,
  type NullableProjection,
  type ProjectionList,
  type ProjectionRef,
  type QueryDef,
  type Watch,
} from "./contract/methods";
export {
  DEFAULT_COLLECTION_LIMIT,
  DEFAULT_COLLECTION_MAX_LIMIT,
  via,
  type CollectionDef,
  type CollectionWhere,
  type OrderBy,
  type SortDirection,
  type ViaScope,
  type Viewer,
  type ViewPredicate,
} from "./contract/collections";
export {
  defineContract,
  type AnyContract,
  type ChannelDef,
  type Contract,
  type ContractDefinition,
  type EventDef,
  type IndexRow,
  type ReservedMethodName,
  type RowSchema,
  type StreamDef,
} from "./contract/defineContract";
// The read/write kit's contract half (RFC 0003 section 12.1); its handlers
// are `crud.handlers` on ./server.
export {
  CRUD_METHODS,
  crud,
  type CrudBulkDelete,
  type CrudBulkUpdate,
  type CrudContractOptions,
  type CrudCreate,
  type CrudDelete,
  type CrudGet,
  type CrudGetMany,
  type CrudInputOptions,
  type CrudList,
  type CrudListOptions,
  type CrudMethodName,
  type CrudMethods,
  type CrudReorder,
  type CrudReorderOptions,
  type CrudTag,
  type CrudToggle,
  type CrudUpdate,
  type ListInput,
  type NumberFieldOf,
  type ScalarFieldOf,
} from "./contract/kits/crud";
export {
  CRUD_MAX_IDS,
  type BulkPatch,
  type BulkResult,
  type IdInput,
  type IdsInput,
  type ReorderInput,
  type WithId,
} from "./contract/kits/crudSchemas";
export {
  LIST_DEFAULT_LIMIT,
  LIST_MAX_LIMIT,
  type FilterValue,
  type ListPage,
  type ListQuery,
  type ListSort,
} from "./contract/kits/crudList";
// The search kit's contract half (RFC 0003 section 12.2); its handlers are
// `search.handlers` on ./server, and the client adds `useSearch` to its member.
export {
  search,
  type SearchContractOptions,
  type SearchDef,
  type SearchMethods,
  type SearchTag,
  type TextFieldOf,
} from "./contract/kits/search";
export {
  SEARCH_DEFAULT_LIMIT,
  SEARCH_DEFAULT_MIN_LENGTH,
  SEARCH_MAX_LIMIT,
  SEARCH_MAX_QUERY_LENGTH,
  type SearchInput,
  type SearchPage,
  type SearchQuery,
} from "./contract/kits/searchSchemas";
export type { KitSchema } from "./contract/kits/schemas";
export type {
  ChannelPayloadOf,
  CollectionName,
  CollectionOf,
  ContractMap,
  EntityOf,
  EventPayloadOf,
  IndexFieldOf,
  IndexRowOf,
  InputOf,
  ItemOf,
  KindOf,
  MethodName,
  MethodOf,
  OutputOf,
  ParsedInputOf,
  ProjectionName,
  ProjectionOf,
  ScopeOf,
  ServiceNameOf,
  StreamItemOf,
  ViewName,
} from "./contract/infer";
export {
  CLIENT_EVENTS,
  SERVER_EVENTS,
  SERVICE_TOPIC,
  collectionRoom,
  collectionTopic,
  entityRoom,
  topicRoom,
  userRoom,
  type ClientEventName,
  type ServerEventName,
} from "./contract/names";

// Protocol v5 (RFC 0003 section 8), also browser-safe. The JSON-only Socket.IO
// parser imports `socket.io-parser`, so it is the separate `./parser` export.
export {
  ERROR_CODES,
  QuickdrawError,
  fromWire,
  httpStatus,
  isErrorCode,
  toWire,
  type ErrorCode,
  type RateLimitedErrorData,
  type ValidationErrorData,
  type WireError,
  type WireIssue,
} from "./protocol/errors";
export {
  PROTOCOL_MISMATCH,
  PROTOCOL_VERSION,
  isAuthenticationRefused,
  isProtocolMismatch,
  isQdHandshake,
  type AuthenticationRefused,
  type HandshakeAuth,
  type HelloFrame,
  type HelloLimits,
  type HelloSubscriptionLimits,
  type ProtocolMismatch,
  type QdHandshake,
} from "./protocol/version";
export {
  isCallEnvelope,
  isCancel,
  type AccessFrame,
  type CallEnvelope,
  type CallId,
  type CallNotModified,
  type CallReply,
  type CallSuccess,
  type CancelFrame,
  type ChangedFrame,
  type ChannelFrame,
  type ClientToServerEvents,
  type CollectionDelta,
  type CollectionFrame,
  type CollectionItemsReply,
  type CollectionItemsRequest,
  type CollectionResumed,
  type CollectionScopeRef,
  type CollectionSnapshot,
  type CollectionSubscribe,
  type CollectionSubscribeReply,
  type EntityFrame,
  type EntityNotModified,
  type EntityPatch,
  type EntityRemove,
  type EntityResult,
  type EntityRow,
  type EntitySubscribe,
  type EntitySubscribeReply,
  type EntityUnsubscribe,
  type EntityUpdate,
  type EventFrame,
  type Failure,
  type Ok,
  type Revision,
  type RevokedFrame,
  type RevokeReason,
  type RotateFrame,
  type ServerToClientEvents,
  type StreamFrame,
  type StreamSubscribe,
  type StreamSubscribeReply,
  type Version,
  type WatchFrame,
  type WireIndexRow,
} from "./protocol/envelope";
