// The 4.x names 5.0 removed or moved, as `@fitzzero/quickdraw-lint`'s
// `no-v4-api` rule lists them (`packages/lint/plugin/rules/no-v4-api.mjs`,
// where each has its replacement). The codemod marks imports that still name
// one; a test keeps these lists equal to the rule's.

/** Names no 5.0 entry point exports. */
export const REMOVED_NAMES: ReadonlySet<string> = new Set([
  "ServiceResponse",
  "ServiceMethodMap",
  "ServiceMethodDefinition",
  "ServiceMethodContext",
  "ExtractPayload",
  "ExtractResponse",
  "ServiceChannelMap",
  "ServiceChannelDefinition",
  "ServiceChannelContext",
  "CHANNEL_EVENT_PREFIX",
  "channelEventName",
  "QuickdrawEventMap",
  "QuickdrawEventName",
  "QuickdrawEventData",
  "QuickdrawUser",
  "ACLEntity",
  "AdminCreatePayload",
  "AdminDeletePayload",
  "AdminDeleteResponse",
  "AdminGetPayload",
  "AdminGetSubscribersPayload",
  "AdminListPayload",
  "AdminListResponse",
  "AdminMetaPayload",
  "AdminMetaResponse",
  "AdminReemitPayload",
  "AdminReemitResponse",
  "AdminSetACLPayload",
  "AdminSubscribersResponse",
  "AdminUnsubscribeAllPayload",
  "AdminUnsubscribeAllResponse",
  "AdminUpdatePayload",
  "SubscribePayload",
  "UnsubscribePayload",
  "CollectionSubscribePayload",
  "CollectionUnsubscribePayload",
  "CollectionSnapshotPage",
  "CollectionSnapshotResponse",
  "serviceRoom",
  "serviceFullRoom",
  "collectionEventName",
  "BaseService",
  "BaseRpcService",
  "BaseServiceInstance",
  "BaseServiceOptions",
  "ServiceRegistry",
  "ServiceRegistryInstance",
  "ServiceRegistryOptions",
  "createQuickdrawServer",
  "QuickdrawServerOptions",
  "QuickdrawServerResult",
  "QuickdrawIdentity",
  "CollectionManager",
  "CollectionDefinition",
  "CollectionWriteEvent",
  "InstallAdminMethodsOptions",
  "PrismaDelegate",
  "zodToAdminFields",
  "getDefaultEntityFields",
  "mergeWithDefaultFields",
  "ZodToAdminFieldsOptions",
  "createMcpRoutes",
  "McpHttpRoutesOptions",
  "generateToolMetadata",
  "GenerateToolMetadataOptions",
  "ServiceToolSpec",
  "MethodSpec",
  "ServiceInfo",
  "ServiceMethodInfo",
  "McpToolDefinition",
  "McpMethodDefinition",
  "McpMethodContext",
  "McpServiceInstance",
  "McpRegistryInstance",
  "useService",
  "useServiceMethod",
  "UseServiceOptions",
  "UseServiceResult",
  "useServiceQuery",
  "UseServiceQueryOptions",
  "UseServiceQueryResult",
  "useSubscription",
  "UseSubscriptionOptions",
  "UseSubscriptionResult",
  "useCollection",
  "useRoomEvents",
  "UseRoomEventsOptions",
  "QuickdrawRoomEventHandlers",
  "useChannelSend",
  "UseChannelSendResult",
  "useQuickdrawSocket",
  "QuickdrawSocketContextValue",
  "getOAuthUrl",
  "logout",
  "logoutAllDevices",
  "ServiceCallError",
  "ClientServiceMethodMap",
  "SubscriptionDataMap",
  "applySnapshot",
  "applyPage",
  "applyDelta",
  "applyDeltas",
  "createEmptyEntry",
  "CollectionCacheEntry",
  "SocketTextField",
  "SocketTextFieldProps",
  "SocketCheckbox",
  "SocketCheckboxProps",
  "SocketSelect",
  "SocketSelectProps",
  "SocketSlider",
  "SocketSliderProps",
  "SocketSwitch",
  "SocketSwitchProps",
  "useSocketInput",
  "UseSocketInputOptions",
  "UseSocketInputResult",
  "CommitMode",
]);

/** Names 5.0 moved off an entry point, by entry point. */
export const MOVED_NAMES: Readonly<Record<string, ReadonlySet<string>>> = {
  "@fitzzero/quickdraw-core/server": new Set([
    "AuthRequest",
    "AuthResponse",
    "CookieResponse",
    "CookieSettings",
    "DEFAULT_MOCK_PATH_PREFIX",
    "DiscordUser",
    "GoogleUser",
    "JWTPayload",
    "MockOAuthProviderOptions",
    "MockOAuthRouter",
    "MockOAuthUser",
    "OAUTH_RETURN_ORIGIN_COOKIE",
    "OAuthConfig",
    "OAuthProvider",
    "OAuthTokenResponse",
    "RegisterMockOAuthOptions",
    "RequireAuthOptions",
    "SESSION_COOKIE",
    "SessionCookieOptions",
    "ValidateOriginOptions",
    "clearSessionCookie",
    "createJWT",
    "createMockOAuthProvider",
    "createOAuthURL",
    "createRequireAuth",
    "discordProvider",
    "exchangeOAuthCode",
    "extractBearerOrCookieToken",
    "getDiscordAvatarUrl",
    "googleProvider",
    "isMockOAuthEnabled",
    "registerMockOAuthProvider",
    "setSessionCookie",
    "validateRedirectOrigin",
    "verifyJWT",
    "bootstrapMcpServer",
    "createMcpStdioServer",
    "McpStdioServerOptions",
    "McpRegistryOptions",
    "McpRegistry",
    "QuickdrawSocket",
  ]),
};

/** Entry points 5.0 removed. */
export const REMOVED_ENTRIES: ReadonlySet<string> = new Set([
  "@fitzzero/quickdraw-core/server/testing",
  "@fitzzero/quickdraw-core/server/testing/prisma",
  "@fitzzero/quickdraw-core/client/testing",
  "@fitzzero/quickdraw-core/eslint-plugin",
  "@fitzzero/quickdraw-core/eslint-config",
]);

/**
 * Removed entry points whose exports live on under another name, unchanged:
 * the codemod rewrites the module specifier.
 */
export const RENAMED_ENTRIES: Readonly<Record<string, string>> = {
  "@fitzzero/quickdraw-core/server/testing/prisma": "@fitzzero/quickdraw-core/testing/prisma",
};

/** 4.x props of `QuickdrawProvider`. */
export const PROVIDER_PROPS: ReadonlySet<string> = new Set([
  "serverUrl",
  "authToken",
  "autoConnect",
  "withCredentials",
  "socketPath",
  "reconnectBehavior",
]);
